name: phpunit

on:
  push:
    branches:
      - 11.x
  pull_request:
    branches:
      - 11.x

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:16.4
        env:
          POSTGRES_PORT: 5432
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel
          TZ: Asia/Tokyo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: php artisan test
